### ISSUE TITLE
[TASK] Implement Character Creation

### ISSUE THREAD

**Issue by GrecoSorcerer** [TheGrecosDev/WOIN-Game-Tools#10]
# Task

- Character creation must be implemented in the woingame.py file.
- The data_entry.py script may be useful in implementing this process.
- Derived Stats and Equipment will likely be left for a later task

# Character Creation Process

- [x] 1. Initialize the character with 3's for all attributes except PSY,MAG, and CHI
- [x] 2. Species Choice
- [ ] 3. Homeworld
- [ ] 4. Hook -> hook attribute
- [ ] 5. Life-Path: Pick an Origin and four Careers
     * Note: your origin may be taken multiple time so long as they are taken in succession.

    - [ ] 5.1. Apply all listed attributes adjustments
      * Note: you may optionally substitute 1 listed attribute with either 1of your Species attributes _or_ your hook attribute. 

    - [ ] 5.2. Pick 2 of the listed skills.
     * Note: you may optionally swap 1 listed skill for a defensive skill.

     - [ ] 5.3. Career Exploit choice or Universal Exploit

     - [ ] 5.4. Roll Age mod
- [ ] 6. Take Exploit: Aim or Feint (Some books and splats provide additional options at this step)
- [ ] 7. Trait choice 
- [ ] 8. Calculate Age
- [ ] 9. Calculate Derived stats **[Not on this task]**
- [ ] 10. Equip your Character **[Not on this task]**

**Comment by GrecoSorcerer** [comment]
Character gets named in woingame.Game.characterBuilder() before step 1
